### ISSUE TITLE
Application crashes on launch without adding a configuration file.

### ISSUE THREAD

**Issue by Gishe** [ITWDiagraph/BoxwriterInterop#29]
The application crashes on launch without adding a production appsetting.json file.

This file should be included in the artifact output by the build if it is required to run the application.

```
Unhandled exception. System.IO.FileNotFoundException: The configuration file 'appsettings.Production.json' was not found and is not optional. The expected physical path was 'E:\Downloads\Application (1)\appsettings.Production.json'.
   at Microsoft.Extensions.Configuration.FileConfigurationProvider.HandleException(ExceptionDispatchInfo info)
   at Microsoft.Extensions.Configuration.FileConfigurationProvider.Load(Boolean reload)
   at Microsoft.Extensions.Configuration.FileConfigurationProvider.Load()
   at Microsoft.Extensions.Configuration.ConfigurationRoot..ctor(IList`1 providers)
   at Microsoft.Extensions.Configuration.ConfigurationBuilder.Build()
   at Microsoft.Extensions.Hosting.HostBuilder.InitializeAppConfiguration()
   at Microsoft.Extensions.Hosting.HostBuilder.Build()
   at Program.<Main>$(String[] args)
```

**Comment by erikgabbard** [comment]
Completed by https://github.com/ITWDiagraph/BoxwriterInterop/pull/33
